apiVersion: app.piny940.com/v1alpha1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: kube-cronjob
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
