name: Build App for Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  prd-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          make docker-build docker-push IMG=ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ github.run_number }}
          make kustomize-build IMG=ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ github.run_number }}
          gh release create ${{ github.sha }}-${{ github.run_number }} manifests.out
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
